package consts

//---------- YT-DLP DOWNLOAD ARGUMENTS --------------
var YT_DLP_DOWNLOAD_ARGS = []string{
	"--merge-output-format", "mp4",
	"--embed-metadata",
	"--write-thumbnail",
	"--user-agent", USER_AGENT_STRING,
	"--referer", "https://www.youtube.com/",
	"--add-header", HEADER_ACCEPT_LANGUAGE,
	"--add-header", HEADER_ACCEPT_ENCODING,
	"--add-header", HEADER_ACCEPT,
	"--add-header", "Sec-Ch-Ua:\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"",
	"--add-header", "Sec-Ch-Ua-Mobile:?0",
	"--add-header", "Sec-Ch-Ua-Platform:\"Windows\"",
	"--geo-bypass",
	"--geo-bypass-country", "US",
	"--extractor-retries", "10",
	"--fragment-retries", "20",
	"--retry-sleep", "exp=1:120",
	"--socket-timeout", "30",
	"--max-downloads", "1",
	"--no-playlist",
	"--no-warnings",
	"--no-check-certificate",
	"--force-ipv4",
	"--newline",
	"--prefer-free-formats",
	"--youtube-skip-dash-manifest",
	"--hls-prefer-native",
}

//---------- YT-DLP MP3 CONVERSION ARGUMENTS --------------
var YT_DLP_MP3_ARGS = []string{
	"-x",
	"--audio-format", "mp3",
	"--audio-quality", "0",
	"--embed-metadata",
	"--user-agent", USER_AGENT_STRING,
	"--referer", "https://www.youtube.com/",
	"--add-header", HEADER_ACCEPT_LANGUAGE,
	"--add-header", HEADER_ACCEPT_ENCODING,
	"--add-header", "Sec-Ch-Ua:\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"",
	"--add-header", "Sec-Ch-Ua-Mobile:?0",
	"--add-header", "Sec-Ch-Ua-Platform:\"Windows\"",
	"--geo-bypass",
	"--geo-bypass-country", "US",
	"--extractor-retries", "10",
	"--fragment-retries", "20",
	"--retry-sleep", "exp=1:120",
	"--socket-timeout", "30",
	"--max-downloads", "1",
	"--no-playlist",
	"--no-warnings",
	"--no-check-certificate",
	"--force-ipv4",
	"--newline",
	"--prefer-free-formats",
	"--youtube-skip-dash-manifest",
	"--hls-prefer-native",
}

//---------- YT-DLP VIDEO INFO ARGUMENTS --------------
var YT_DLP_INFO_ARGS = []string{
	"-j",
	"--no-warnings",
	"--user-agent", USER_AGENT_STRING,
	"--referer", "https://www.youtube.com/",
	"--add-header", HEADER_ACCEPT_LANGUAGE,
	"--add-header", HEADER_ACCEPT_ENCODING,
	"--add-header", "Sec-Ch-Ua:\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"",
	"--add-header", "Sec-Ch-Ua-Mobile:?0",
	"--add-header", "Sec-Ch-Ua-Platform:\"Windows\"",
	"--geo-bypass",
	"--geo-bypass-country", "US",
	"--extractor-retries", "10",
	"--fragment-retries", "10",
	"--retry-sleep", "exp=1:120",
	"--no-check-certificate",
	"--force-ipv4",
	"--prefer-free-formats",
	"--youtube-skip-dash-manifest",
}